/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.dashboard;

import sk.stu.fiit.gui.utils.DashboardItem;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JPanel;
import sk.stu.fiit.gui.MainWindow;

/**
 *
 * @author dlhyl
 */
public class DashboardPanel extends javax.swing.JPanel {
    private final MainWindow main;
    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel(MainWindow main) {
        this.main = main;
        setOpaque(false);
        initComponents();
        addMenuItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void addMenuItems() {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle");
        JPanel novyVyletCard = new DashboardItem(this.main, "cardNovyVylet", "vylet.png", bundle.getString("NOVÝ VÝLET"));
        GridBagConstraints c1 = new GridBagConstraints();
        c1.gridx=0;c1.gridy=0;c1.gridheight=1;c1.gridwidth=1;c1.insets=new Insets(25,25,25,25);
        this.add(novyVyletCard,c1);

        JPanel mojeVyletyCard = new DashboardItem(this.main, "cardMojeVylety","list.png", bundle.getString("MOJE VÝLETY"));
        GridBagConstraints c2 = new GridBagConstraints();
        c2.gridx=1;c2.gridy=0;c2.gridheight=1;c2.gridwidth=1;c2.insets=new Insets(25,25,25,25);
        this.add(mojeVyletyCard, c2);

        JPanel leaderboardCard = new DashboardItem(this.main, "cardRebricek", "leaderboard.png", bundle.getString("REBRÍČEK"));
        GridBagConstraints c6 = new GridBagConstraints();
        c6.gridx=2;c6.gridy=1;c6.gridheight=1;c6.gridwidth=1;c6.insets=new Insets(25,25,25,25);
        this.add(leaderboardCard, c6);

        JPanel pozvankyCard = new DashboardItem(this.main, "cardPozvanky","invitation.png", bundle.getString("POZVÁNKY"));
        GridBagConstraints c3 = new GridBagConstraints();
        c3.gridx=2;c3.gridy=0;c3.gridheight=1;c3.gridwidth=1;c3.insets=new Insets(25,25,25,25);
        this.add(pozvankyCard,c3);

        JPanel statistikyCard = new DashboardItem(this.main, "cardStatistiky","statistics.png",  bundle.getString("ŠTATISTIKY"));
        GridBagConstraints c4 = new GridBagConstraints();
        c4.gridx=0;c4.gridy=1;c4.gridheight=1;c4.gridwidth=1;c4.insets=new Insets(25,25,25,25);
        this.add(statistikyCard,c4);

        JPanel odznakyCard = new DashboardItem(this.main, "cardOdznaky","badge.png", bundle.getString("ODZNAKY"));
        GridBagConstraints c5 = new GridBagConstraints();
        c5.gridx=1;c5.gridy=1;c5.gridheight=1;c5.gridwidth=1;c5.insets=new Insets(25,25,25,25);
        this.add(odznakyCard, c5);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
