/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils;

import java.awt.Color;
import javax.swing.ImageIcon;
import sk.stu.fiit.app.user.Odznak;
import sk.stu.fiit.app.user.Vyletnik;

/**
 *
 * @author dlhyl
 */
public class BadgeItem extends RoundedPanel {
    private final Odznak odznak;
    private final Vyletnik vyletnik;
    /**
     * Creates new form StatistikaItem
     */
    public BadgeItem(Odznak o, Vyletnik v) {
        super(40, new Color(0,0,0,100));
        this.vyletnik = v;
        this.odznak = o;
        initComponents();
        
        if (vyletnik.hasOdznak(odznak)) {
            ((RoundedPanel)pnlContent).setBackgroundColor(new Color(0,0,0,0));
            lblLock.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContent = new RoundedPanel(40, new Color(0,0,0,160));
        lblLock = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 0));
        lblDescription = new javax.swing.JLabel();
        lblReward = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        pnlContent.setMinimumSize(new java.awt.Dimension(300, 300));
        pnlContent.setOpaque(false);
        pnlContent.setPreferredSize(new java.awt.Dimension(260, 260));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(pnlContent, gridBagConstraints);

        lblLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/badge-locked.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(lblLock, gridBagConstraints);

        lblIcon.setFont(new java.awt.Font("Gill Sans MT", 1, 45)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(255, 102, 102));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/badge/"+odznak.getIkonka())));
        lblIcon.setMaximumSize(new java.awt.Dimension(128, 128));
        lblIcon.setMinimumSize(new java.awt.Dimension(128, 128));
        lblIcon.setPreferredSize(new java.awt.Dimension(128, 128));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(lblIcon, gridBagConstraints);

        filler2.setBackground(new Color(255,102,102));
        filler2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 35, 5, 35);
        add(filler2, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 204, 204));
        lblDescription.setText(odznak.getPopis());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        add(lblDescription, gridBagConstraints);

        lblReward.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblReward.setForeground(new java.awt.Color(212, 175, 55));
        lblReward.setText("+"+String.valueOf(odznak.getPointy())+" bodov");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(lblReward, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLock;
    private javax.swing.JLabel lblReward;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}