/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils;

import java.awt.Color;
import sk.stu.fiit.gui.MainWindow;

/**
 *
 * @author dlhyl
 */
public class DashboardItem extends RoundedPanel {
    private final String img;
    private final String name;
    private final String cardName;
    private final MainWindow m;
    /**
     * Creates new form DashboardItem
     */
    public DashboardItem(MainWindow m, String cardName, String img, String name) {
        super(80, new Color(144,30,57,180));
        this.img = img;
        this.name = name;
        this.cardName = cardName;
        this.m = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblIcon = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 0));
        lblName = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(230, 250));
        setMinimumSize(new java.awt.Dimension(230, 250));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(230, 250));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/"+this.img)));
        lblIcon.setMinimumSize(new java.awt.Dimension(128, 128));
        lblIcon.setPreferredSize(new java.awt.Dimension(128, 128));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(52, 0, 0, 0);
        add(lblIcon, gridBagConstraints);

        filler2.setBackground(new Color(255,102,102));
        filler2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 97, 0, 97);
        add(filler2, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(230, 230, 230));
        lblName.setText(this.name);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 53, 0);
        add(lblName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        this.m.changeDashboardScreen(this.cardName);
    }//GEN-LAST:event_formMouseReleased

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
