/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author dlhyl
 */
public class StatistikaItem extends RoundedPanel {
    private final String name;
    private final String value;
    /**
     * Creates new form StatistikaItem
     */
    public StatistikaItem(String name, String value) {
        super(40, new Color(0,0,0,100));
        this.name=name;
        this.value=value;
        initComponents();
    }
    
    public StatistikaItem(String name, int value) {
        super(40, new Color(0,0,0,100));
        this.name=name;
        this.value=String.valueOf(value);
        initComponents();
    }
    
    public StatistikaItem(String name, double value) {
        super(40, new Color(0,0,0,100));
        this.name=name;
        DecimalFormat df = new DecimalFormat("0.00");
        this.value=df.format(value);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblValue = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 0));
        lblName = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblValue.setFont(new java.awt.Font("Gill Sans MT", 1, 45)); // NOI18N
        lblValue.setForeground(new java.awt.Color(255, 204, 204));
        lblValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue.setText(this.value);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(lblValue, gridBagConstraints);

        filler2.setBackground(new Color(255,102,102));
        filler2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 35, 5, 35);
        add(filler2, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Gill Sans MT", 1, 28)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 102, 102));
        lblName.setText(this.name);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        add(lblName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
