/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import sk.stu.fiit.gui.utils.RoundedPanel;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sk.stu.fiit.app.CustomLogger;
import sk.stu.fiit.app.Potulkor;
import sk.stu.fiit.app.user.Pouzivatel;

/**
 *
 * @author dlhyl
 */
public class LoginPanel extends javax.swing.JPanel {
    private SplashPanel splashPanel;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(SplashPanel s) {
        this.splashPanel = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLogin = new RoundedPanel(60,new Color(0, 0, 0, 150));
        inputLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblHeslo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pwField = new javax.swing.JPasswordField();
        lblBack = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        pnlLogin.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlLogin.setOpaque(false);
        pnlLogin.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlLogin.setLayout(new java.awt.GridBagLayout());

        inputLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        pnlLogin.add(inputLogin, gridBagConstraints);

        lblLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 102, 102));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblLogin.setText(bundle.getString("LOGIN")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        pnlLogin.add(lblLogin, gridBagConstraints);

        lblHeslo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblHeslo.setForeground(new java.awt.Color(255, 102, 102));
        lblHeslo.setText(bundle.getString("HESLO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        pnlLogin.add(lblHeslo, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(144, 30, 57));
        btnLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 204, 204));
        btnLogin.setText(bundle.getString("PRIHLÁSIŤ")); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        pnlLogin.add(btnLogin, gridBagConstraints);

        pwField.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        pnlLogin.add(pwField, gridBagConstraints);

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(200, 200, 200));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/previous.png"))); // NOI18N
        lblBack.setText(bundle.getString("SPÄŤ")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 2.5;
        gridBagConstraints.weighty = 1.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 5, 30);
        pnlLogin.add(lblBack, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(pnlLogin, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        this.splashPanel.setDefaultCard();
    }//GEN-LAST:event_lblBackMouseReleased

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        String login = inputLogin.getText();
        String pw = String.valueOf(pwField.getPassword());
        JLabel label = new JLabel();
        label.setFont(new Font("Gill Sans MT", Font.BOLD, 18));
        if (login.isEmpty() || pw.isEmpty()) {
            label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyplnte_polia"));
            JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[Login] nie su vyplnene vsetky udaje");
            return;
        }
        
        Potulkor p = ((MainWindow)this.splashPanel.getMainWindow()).getPotulkor();
        Pouzivatel user = p.getPouzivatel(login, pw);
        if (user == null) {
            label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("heslo_error_zle"));
            JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[Login] zle prihlasovacie udaje");
            return;
        }
        CustomLogger.getLogger().log(Level.INFO, "[Login] prihlaseny pouzivatel: "+user.getLogin());
        ((MainWindow)this.splashPanel.getMainWindow()).login(user);
    }//GEN-LAST:event_btnLoginMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblHeslo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pwField;
    // End of variables declaration//GEN-END:variables
}
