/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import sk.stu.fiit.gui.utils.RoundedPanel;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import sk.stu.fiit.app.CustomLogger;
import sk.stu.fiit.app.user.Pouzivatel;
import sk.stu.fiit.app.user.Pouzivatel.Pohlavie;
import sk.stu.fiit.gui.utils.RoundedImage;

/**
 *
 * @author dlhyl
 */
public class ProfilPanel extends JPanel {

    private MainWindow m;
    private Pouzivatel p;
    private final int imageSize = 200;
    /**
     * Creates new form NovyVyletPanel
     */
    public ProfilPanel(MainWindow m) {
        this.m = m;
        initComponents();
        updateScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitle = new RoundedPanel(20, new Color(101, 21, 40, 180));
        lblTitle = new javax.swing.JLabel();
        pnlContent = new RoundedPanel(50, new Color(144,30,57,180));
        lblBack = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        lblMeno = new javax.swing.JLabel();
        lblPriezvisko = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lnlNoveHeslo = new javax.swing.JLabel();
        lblPotvrdteHeslo = new javax.swing.JLabel();
        lblMenoContent = new javax.swing.JLabel();
        lblPriezviskoContent = new javax.swing.JLabel();
        lblLoginContent = new javax.swing.JLabel();
        pwField1 = new javax.swing.JPasswordField();
        pwField2 = new javax.swing.JPasswordField();
        btnChangePw = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        btnChangePic = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        lblPohlavie = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        pnlTitle.setMaximumSize(new java.awt.Dimension(0, 0));
        pnlTitle.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlTitle.setOpaque(false);
        pnlTitle.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlTitle.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 204, 204));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblTitle.setText(bundle.getString("MÔJ PROFIL")); // NOI18N
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        pnlTitle.add(lblTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(80, 100, -1, 100);
        add(pnlTitle, gridBagConstraints);

        pnlContent.setOpaque(false);
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(200, 200, 200));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/previous.png"))); // NOI18N
        lblBack.setText(bundle.getString("SPÄŤ")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 25);
        pnlContent.add(lblBack, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.weightx = 1.0;
        pnlContent.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.weightx = 1.0;
        pnlContent.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        pnlContent.add(filler3, gridBagConstraints);

        lblMeno.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblMeno.setForeground(new java.awt.Color(255, 102, 102));
        lblMeno.setText(bundle.getString("MENO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        pnlContent.add(lblMeno, gridBagConstraints);

        lblPriezvisko.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblPriezvisko.setForeground(new java.awt.Color(255, 102, 102));
        lblPriezvisko.setText(bundle.getString("PRIEZVISKO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        pnlContent.add(lblPriezvisko, gridBagConstraints);

        lblLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 102, 102));
        lblLogin.setText(bundle.getString("LOGIN")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        pnlContent.add(lblLogin, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(144, 30, 57));
        jSeparator1.setForeground(new java.awt.Color(144, 30, 57));
        jSeparator1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlContent.add(jSeparator1, gridBagConstraints);

        lnlNoveHeslo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lnlNoveHeslo.setForeground(new java.awt.Color(255, 102, 102));
        lnlNoveHeslo.setText(bundle.getString("NOVÉ HESLO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        pnlContent.add(lnlNoveHeslo, gridBagConstraints);

        lblPotvrdteHeslo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblPotvrdteHeslo.setForeground(new java.awt.Color(255, 102, 102));
        lblPotvrdteHeslo.setText(bundle.getString("POTVRĎTE HESLO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        pnlContent.add(lblPotvrdteHeslo, gridBagConstraints);

        lblMenoContent.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblMenoContent.setForeground(new java.awt.Color(255, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        pnlContent.add(lblMenoContent, gridBagConstraints);

        lblPriezviskoContent.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblPriezviskoContent.setForeground(new java.awt.Color(255, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        pnlContent.add(lblPriezviskoContent, gridBagConstraints);

        lblLoginContent.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblLoginContent.setForeground(new java.awt.Color(255, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 16);
        pnlContent.add(lblLoginContent, gridBagConstraints);

        pwField1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 16);
        pnlContent.add(pwField1, gridBagConstraints);

        pwField2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 16);
        pnlContent.add(pwField2, gridBagConstraints);

        btnChangePw.setBackground(new java.awt.Color(144, 30, 57));
        btnChangePw.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnChangePw.setForeground(new java.awt.Color(255, 204, 204));
        btnChangePw.setText(bundle.getString("ZMENIŤ HESLO")); // NOI18N
        btnChangePw.setMaximumSize(new java.awt.Dimension(200, 45));
        btnChangePw.setMinimumSize(new java.awt.Dimension(200, 45));
        btnChangePw.setPreferredSize(new java.awt.Dimension(200, 45));
        btnChangePw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangePwMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        pnlContent.add(btnChangePw, gridBagConstraints);

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setAlignmentX(0.5F);
        lblPicture.setMinimumSize(new java.awt.Dimension(150, 150));
        lblPicture.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlContent.add(lblPicture, gridBagConstraints);

        btnChangePic.setBackground(new java.awt.Color(144, 30, 57));
        btnChangePic.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnChangePic.setForeground(new java.awt.Color(255, 204, 204));
        btnChangePic.setText(bundle.getString("ZMENIŤ OBRÁZOK")); // NOI18N
        btnChangePic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangePicMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlContent.add(btnChangePic, gridBagConstraints);

        lblGender.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 102, 102));
        lblGender.setText(bundle.getString("POHLAVIE")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        pnlContent.add(lblGender, gridBagConstraints);

        lblPohlavie.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblPohlavie.setForeground(new java.awt.Color(255, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        pnlContent.add(lblPohlavie, gridBagConstraints);

        btnLogout.setBackground(new java.awt.Color(144, 30, 57));
        btnLogout.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 204, 204));
        btnLogout.setText(bundle.getString("ODHLÁSIŤ SA")); // NOI18N
        btnLogout.setPreferredSize(new java.awt.Dimension(160, 50));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        pnlContent.add(btnLogout, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 10.0;
        pnlContent.add(filler4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 100, 100);
        add(pnlContent, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        this.m.changeDashboardScreen("cardDashboardMenu");
    }//GEN-LAST:event_lblBackMouseReleased

    private void btnChangePicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePicMouseReleased
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            try {
                File file = fileChooser.getSelectedFile();
                BufferedImage subimage;
                BufferedImage image = ImageIO.read(file.getAbsoluteFile());
                int w = image.getWidth();
                int h = image.getHeight();
                if (w > h) {
                    subimage = image.getSubimage((w-h)/2, 0, h, h);
                }  else {
                    subimage = image.getSubimage(0, (h-w)/2, w, w);
                }
                if (this.p!=null)
                    this.p.setObrazok(new ImageIcon(subimage.getScaledInstance(this.imageSize, this.imageSize, Image.SCALE_SMOOTH)));
                showImage();
                this.m.changeProfileLabelIcon();
                CustomLogger.getLogger().log(Level.INFO, "[Picture change] user:"+this.p.getLogin());
            } catch (IOException ex) {
                Logger.getLogger(ProfilPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnChangePicMouseReleased

    private void btnChangePwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePwMouseReleased
        String pw1 = String.valueOf(pwField1.getPassword());
        String pw2 = String.valueOf(pwField2.getPassword());
        
        JLabel label = new JLabel();
        label.setFont(new Font("Gill Sans MT", Font.BOLD, 18));
        
        if (pw1.isEmpty() || pw2.isEmpty()) {
            label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyplnte_heslo"));
            JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[Change password] nevyplnene heslo, user:" + this.p.getLogin());
            return;
        }
        
        if (!pw1.equals(pw2)) {
            label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("heslo_error_rozne"));
            JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[Change password] hesla sa nezhoduju, user:" + this.p.getLogin());
            return;
        }
        
        if (!Pouzivatel.isValidPassword(pw1)) { 
            label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("heslo_error"));
            JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[Change password] neplatne heslo, user:" + this.p.getLogin());
            return;
        }
        CustomLogger.getLogger().log(Level.INFO, "[Password change] "+this.p.getLogin());
        this.p.setPassword(pw1);
        label.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("heslo_zmena_ok"));
        JOptionPane.showMessageDialog(this.getParent(),label,java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("USPECH"),JOptionPane.INFORMATION_MESSAGE);
        pwField1.setText("");
        pwField2.setText("");
    }//GEN-LAST:event_btnChangePwMouseReleased

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        CustomLogger.getLogger().log(Level.INFO, "[Log out] "+this.m.getLoggedInPouzivatel().getLogin());
        this.m.logout();
    }//GEN-LAST:event_btnLogoutMouseReleased

    private void updateScreen() {
        Pouzivatel p = this.m.getLoggedInPouzivatel();
        this.p = p;
        
        if (p == null) {
            return;
        }
        showImage();
        pwField1.setText("");
        pwField2.setText("");
        lblPohlavie.setText(p.getPohlavie().equals(Pohlavie.MUZ)?java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("MUŽ"):java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("ŽENA"));
        lblMenoContent.setText(p.getMeno());
        lblPriezviskoContent.setText(p.getPriezvisko());
        lblLoginContent.setText(p.getLogin());
    }
    
    private void showImage() {
        if (p == null) return;
        ImageIcon imageIcon;
        if (p.getObrazok() == null) {
            imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/profile-user-256.png")).getImage().getScaledInstance(this.imageSize,this.imageSize, Image.SCALE_DEFAULT));
        } else {
            imageIcon = RoundedImage.getImage(p.getObrazok(), this.imageSize);
        }
        lblPicture.setIcon(imageIcon);     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePic;
    private javax.swing.JButton btnChangePw;
    private javax.swing.JButton btnLogout;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginContent;
    private javax.swing.JLabel lblMeno;
    private javax.swing.JLabel lblMenoContent;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPohlavie;
    private javax.swing.JLabel lblPotvrdteHeslo;
    private javax.swing.JLabel lblPriezvisko;
    private javax.swing.JLabel lblPriezviskoContent;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lnlNoveHeslo;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPasswordField pwField1;
    private javax.swing.JPasswordField pwField2;
    // End of variables declaration//GEN-END:variables
}
