/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author dlhyl
 */
public class SplashPanel extends javax.swing.JPanel {
    private MainWindow main;
    /**
     * Creates new form SplashPage
     */
    public SplashPanel(MainWindow m) {
        this.main = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cbLanguage = new javax.swing.JComboBox<>();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 5), new java.awt.Dimension(0, 0));
        pnlContent = new javax.swing.JPanel();
        pnlSplashPage = new javax.swing.JPanel();
        lblPlanTrip = new javax.swing.JLabel();
        lblSimpleAndFast = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        backGround = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 960));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1280, 960));
        setLayout(new java.awt.GridBagLayout());

        cbLanguage.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                main.changeLanguage((String)cbLanguage.getSelectedItem());
                changeLanguage();
            }
        });
        cbLanguage.setBackground(new java.awt.Color(144, 30, 57));
        cbLanguage.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        cbLanguage.setForeground(new java.awt.Color(255, 204, 204));
        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SK", "EN" }));
        cbLanguage.setBorder(null);
        cbLanguage.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 30);
        add(cbLanguage, gridBagConstraints);

        pnlHeader.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlHeader.setName(""); // NOI18N
        pnlHeader.setOpaque(false);
        pnlHeader.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlHeader.setLayout(new java.awt.GridBagLayout());

        lblTitle.setBackground(new java.awt.Color(144, 30, 57));
        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 80)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(144, 30, 57));
        lblTitle.setText("Potulky");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        pnlHeader.add(lblTitle, gridBagConstraints);

        filler1.setBackground(new java.awt.Color(144, 30, 57));
        filler1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 65, 0, 0);
        pnlHeader.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        add(pnlHeader, gridBagConstraints);

        pnlContent.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlContent.setOpaque(false);
        pnlContent.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlSplashPage.setOpaque(false);
        pnlSplashPage.setLayout(new java.awt.GridBagLayout());

        lblPlanTrip.setBackground(new java.awt.Color(144, 30, 57));
        lblPlanTrip.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblPlanTrip.setForeground(new java.awt.Color(144, 30, 57));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblPlanTrip.setText(bundle.getString("NAPLÁNUJTE SVOJ VÝLET")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        pnlSplashPage.add(lblPlanTrip, gridBagConstraints);

        lblSimpleAndFast.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        lblSimpleAndFast.setForeground(new java.awt.Color(255, 102, 102));
        lblSimpleAndFast.setText(bundle.getString("JEDNODUCHO A RÝCHLO.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        pnlSplashPage.add(lblSimpleAndFast, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(144, 30, 57));
        btnRegister.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 204, 204));
        btnRegister.setText(bundle.getString("REGISTROVAŤ")); // NOI18N
        btnRegister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.setBorderPainted(false);
        btnRegister.setPreferredSize(new java.awt.Dimension(170, 55));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegisterMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 100, 0, 0);
        pnlSplashPage.add(btnRegister, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(144, 30, 57));
        btnLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 204, 204));
        btnLogin.setText(bundle.getString("PRIHLÁSIŤ")); // NOI18N
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.setBorderPainted(false);
        btnLogin.setPreferredSize(new java.awt.Dimension(170, 55));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlSplashPage.add(btnLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlSplashPage.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 200;
        pnlSplashPage.add(filler3, gridBagConstraints);

        pnlContent.add(pnlSplashPage, "defaultCard");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        add(pnlContent, gridBagConstraints);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/background.png"))); // NOI18N
        backGround.setMaximumSize(new java.awt.Dimension(0, 0));
        backGround.setMinimumSize(new java.awt.Dimension(0, 0));
        backGround.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(backGround, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        JPanel loginPanel = new LoginPanel(this);
        loginPanel.setOpaque(false);
        cbLanguage.setVisible(false);
        pnlContent.add(loginPanel, "loginCard");
        CardLayout c = (CardLayout)pnlContent.getLayout();
        c.show(pnlContent, "loginCard");
    }//GEN-LAST:event_btnLoginMouseReleased

    private void btnRegisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseReleased
        JPanel regPanel = new RegisterPanel(this);
        regPanel.setOpaque(false);
        cbLanguage.setVisible(false);
        pnlContent.add(regPanel, "registerCard");
        CardLayout c = (CardLayout)pnlContent.getLayout();
        c.show(pnlContent, "registerCard");
    }//GEN-LAST:event_btnRegisterMouseReleased

    protected void setDefaultCard() {
        CardLayout c = (CardLayout)pnlContent.getLayout();
        cbLanguage.setVisible(true);
        c.show(pnlContent, "defaultCard");
    }
    
    protected MainWindow getMainWindow() {
        return this.main;
    }
    
    private void changeLanguage() {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle");
        lblPlanTrip.setText(bundle.getString("NAPLÁNUJTE SVOJ VÝLET")); // NOI18N
        lblSimpleAndFast.setText(bundle.getString("JEDNODUCHO A RÝCHLO.")); // NOI18N
        btnRegister.setText(bundle.getString("REGISTROVAŤ")); // NOI18N
        btnLogin.setText(bundle.getString("PRIHLÁSIŤ")); // NOI18N
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel lblPlanTrip;
    private javax.swing.JLabel lblSimpleAndFast;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSplashPage;
    // End of variables declaration//GEN-END:variables
}
