/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.vylet_dashboard;

import sk.stu.fiit.gui.utils.CellRenderers.UlohyListCellRenderer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.time.LocalDate;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sk.stu.fiit.app.CustomLogger;
import sk.stu.fiit.app.trip.Uloha;
import sk.stu.fiit.app.trip.Vylet;
import sk.stu.fiit.app.user.Vyletnik;
import sk.stu.fiit.gui.utils.CustomDialog;
import sk.stu.fiit.gui.utils.CustomScrollBarUI;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class VyletRozpocetPanel extends RoundedPanel {
    private final VyletDashboardPanel m;
    private final Vylet v;
    /**
     * Creates new form VyletMapaPanel
     */
    public VyletRozpocetPanel(VyletDashboardPanel m, Vylet v) {
        super(50, new Color(144,30,57,180));
        this.m = m; 
        this.v = v;
        setOpaque(false);
        initComponents();
        checkControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlAllTasks =  new RoundedPanel(50, new Color(0,0,0,100));
        lblAllTasks = new javax.swing.JLabel();
        scrollAllTasks = new javax.swing.JScrollPane();
        DefaultListModel dlm_au = new DefaultListModel();
        for (Uloha u : v.getRozpocet().getZoznamUloh())
        dlm_au.addElement(u);
        listAllTasks = new javax.swing.JList<>(dlm_au);
        btnTaskAdd = new javax.swing.JButton();
        pnlYourTasks =  new RoundedPanel(50, new Color(0,0,0,100));
        lblYouTasks = new javax.swing.JLabel();
        srollYourTasks = new javax.swing.JScrollPane();
        DefaultListModel dlm_vu = new DefaultListModel();
        for (Uloha u : v.getRozpocet().getZoznamUloh((Vyletnik)m.getHlavneOkno().getLoggedInPouzivatel()))
        dlm_vu.addElement(u);
        listYourTasks = new javax.swing.JList<>(dlm_vu);
        btnTaskComplete = new javax.swing.JButton();
        pnlOverview = new RoundedPanel(50, new Color(0,0,0,100));
        lblVylet = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        lblTasks = new javax.swing.JLabel();
        lblTasksTotal = new javax.swing.JLabel();
        lblBudgetPerMember = new javax.swing.JLabel();
        lblYourTasksCount = new javax.swing.JLabel();
        pnlNewTask =  new RoundedPanel(50, new Color(0,0,0,100));
        inputName = new javax.swing.JTextField();
        inputDesc = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        cbWant = new javax.swing.JCheckBox();
        lblPrice = new javax.swing.JLabel();
        spinnerPrice = new javax.swing.JSpinner();
        btnTaskCreate = new javax.swing.JButton();
        lblNewTask = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        cbNoPrice = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(200, 200, 200));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/previous.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblBack.setText(bundle.getString("SPÄŤ")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 25);
        add(lblBack, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(bundle.getString("ROZPOČET")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        add(lblTitle, gridBagConstraints);

        pnlAllTasks.setOpaque(false);
        pnlAllTasks.setLayout(new java.awt.GridBagLayout());

        lblAllTasks.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblAllTasks.setForeground(new java.awt.Color(255, 204, 204));
        lblAllTasks.setText(bundle.getString("VŠETKY ÚLOHY")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        pnlAllTasks.add(lblAllTasks, gridBagConstraints);

        scrollAllTasks.setOpaque(false);
        scrollAllTasks.getViewport().setOpaque(false);
        scrollAllTasks.setViewportBorder(null);
        scrollAllTasks.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scrollAllTasks.setMinimumSize(new java.awt.Dimension(100, 80));
        scrollAllTasks.setOpaque(false);
        scrollAllTasks.setPreferredSize(new java.awt.Dimension(100, 0));
        scrollAllTasks.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        scrollAllTasks.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        listAllTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listAllTasks.setOpaque(false);
        listAllTasks.setVisibleRowCount(4);
        listAllTasks.setCellRenderer(new UlohyListCellRenderer());
        scrollAllTasks.setViewportView(listAllTasks);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        pnlAllTasks.add(scrollAllTasks, gridBagConstraints);

        btnTaskAdd.setBackground(new java.awt.Color(144, 30, 57));
        btnTaskAdd.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnTaskAdd.setForeground(new java.awt.Color(255, 204, 204));
        btnTaskAdd.setText(bundle.getString("CHCEM ZAOBSTARAŤ")); // NOI18N
        btnTaskAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTaskAddMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlAllTasks.add(btnTaskAdd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlAllTasks, gridBagConstraints);

        pnlYourTasks.setOpaque(false);
        pnlYourTasks.setLayout(new java.awt.GridBagLayout());

        lblYouTasks.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblYouTasks.setForeground(new java.awt.Color(255, 204, 204));
        lblYouTasks.setText(bundle.getString("VAŠE ÚLOHY")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        pnlYourTasks.add(lblYouTasks, gridBagConstraints);

        srollYourTasks.setOpaque(false);
        srollYourTasks.getViewport().setOpaque(false);
        srollYourTasks.setViewportBorder(null);
        srollYourTasks.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        srollYourTasks.setMinimumSize(new java.awt.Dimension(100, 80));
        srollYourTasks.setOpaque(false);
        srollYourTasks.setPreferredSize(new java.awt.Dimension(100, 0));
        srollYourTasks.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        srollYourTasks.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        listYourTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listYourTasks.setOpaque(false);
        listYourTasks.setVisibleRowCount(4);
        listYourTasks.setCellRenderer(new UlohyListCellRenderer());
        srollYourTasks.setViewportView(listYourTasks);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        pnlYourTasks.add(srollYourTasks, gridBagConstraints);

        btnTaskComplete.setBackground(new java.awt.Color(144, 30, 57));
        btnTaskComplete.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnTaskComplete.setForeground(new java.awt.Color(255, 204, 204));
        btnTaskComplete.setText(bundle.getString("SPLNIŤ")); // NOI18N
        btnTaskComplete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTaskCompleteMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlYourTasks.add(btnTaskComplete, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlYourTasks, gridBagConstraints);

        pnlOverview.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlOverview.setOpaque(false);
        pnlOverview.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlOverview.setLayout(new java.awt.GridBagLayout());

        lblVylet.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblVylet.setForeground(new java.awt.Color(255, 204, 204));
        lblVylet.setText(bundle.getString("VÝDAVKY")); // NOI18N
        lblVylet.setMaximumSize(null);
        lblVylet.setMinimumSize(null);
        lblVylet.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        pnlOverview.add(lblVylet, gridBagConstraints);

        lblBudget.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblBudget.setForeground(new java.awt.Color(255, 204, 204));
        lblBudget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBudget.setText(v.getRozpocet().getSumaString()+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("€"));
        lblBudget.setMaximumSize(null);
        lblBudget.setMinimumSize(null);
        lblBudget.setName(""); // NOI18N
        lblBudget.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        pnlOverview.add(lblBudget, gridBagConstraints);

        lblTasks.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblTasks.setForeground(new java.awt.Color(255, 204, 204));
        lblTasks.setText(bundle.getString("ÚLOHY")); // NOI18N
        lblTasks.setMaximumSize(null);
        lblTasks.setMinimumSize(null);
        lblTasks.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        pnlOverview.add(lblTasks, gridBagConstraints);

        lblTasksTotal.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTasksTotal.setForeground(new java.awt.Color(255, 204, 204));
        lblTasksTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTasksTotal.setText(String.valueOf(v.getRozpocet().getZoznamUloh().size())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString(" (CELKOVO)"));
        lblTasksTotal.setMaximumSize(null);
        lblTasksTotal.setMinimumSize(null);
        lblTasksTotal.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 15, 0);
        pnlOverview.add(lblTasksTotal, gridBagConstraints);

        lblBudgetPerMember.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblBudgetPerMember.setForeground(new java.awt.Color(229, 204, 255));
        lblBudgetPerMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBudgetPerMember.setText(v.getRozpocet().getSumaString(v.getPocetUcastnikov())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("€"));
        lblBudgetPerMember.setMaximumSize(null);
        lblBudgetPerMember.setMinimumSize(null);
        lblBudgetPerMember.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        pnlOverview.add(lblBudgetPerMember, gridBagConstraints);

        lblYourTasksCount.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblYourTasksCount.setForeground(new java.awt.Color(229, 204, 255));
        lblYourTasksCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourTasksCount.setText(String.valueOf(v.getRozpocet().getZoznamUloh((Vyletnik)this.m.getHlavneOkno().getLoggedInPouzivatel()).size())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString(" (VAŠICH)"));
        lblYourTasksCount.setMaximumSize(null);
        lblYourTasksCount.setMinimumSize(null);
        lblYourTasksCount.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 15, 0);
        pnlOverview.add(lblYourTasksCount, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlOverview, gridBagConstraints);

        pnlNewTask.setOpaque(false);
        pnlNewTask.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlNewTask.setLayout(new java.awt.GridBagLayout());

        inputName.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        inputName.setForeground(new java.awt.Color(101, 21, 40));
        inputName.setPreferredSize(new java.awt.Dimension(0, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(inputName, gridBagConstraints);

        inputDesc.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        inputDesc.setForeground(new java.awt.Color(101, 21, 40));
        inputDesc.setPreferredSize(new java.awt.Dimension(0, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(inputDesc, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 102, 102));
        lblName.setText(bundle.getString("NÁZOV")); // NOI18N
        lblName.setPreferredSize(new java.awt.Dimension(0, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(lblName, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 102, 102));
        lblDescription.setText(bundle.getString("KOMENTÁR")); // NOI18N
        lblDescription.setPreferredSize(new java.awt.Dimension(0, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(lblDescription, gridBagConstraints);

        cbWant.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        cbWant.setForeground(new java.awt.Color(255, 204, 204));
        cbWant.setText(bundle.getString("CHCEM ZAOBSTARAŤ")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        pnlNewTask.add(cbWant, gridBagConstraints);

        lblPrice.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 102, 102));
        lblPrice.setText(bundle.getString("CENA")); // NOI18N
        lblPrice.setPreferredSize(new java.awt.Dimension(0, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(lblPrice, gridBagConstraints);

        spinnerPrice.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        spinnerPrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        spinnerPrice.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerPrice, "0.00"));
        spinnerPrice.setPreferredSize(new java.awt.Dimension(0, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        pnlNewTask.add(spinnerPrice, gridBagConstraints);

        btnTaskCreate.setBackground(new java.awt.Color(101, 21, 40));
        btnTaskCreate.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        btnTaskCreate.setForeground(new java.awt.Color(255, 204, 204));
        btnTaskCreate.setText(bundle.getString("PRIDAŤ ÚLOHU")); // NOI18N
        btnTaskCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTaskCreateMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 25);
        pnlNewTask.add(btnTaskCreate, gridBagConstraints);

        lblNewTask.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblNewTask.setForeground(new java.awt.Color(255, 204, 204));
        lblNewTask.setText(bundle.getString("NOVÁ ÚLOHA")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 10, 15);
        pnlNewTask.add(lblNewTask, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.weightx = 0.2;
        pnlNewTask.add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.weightx = 0.2;
        pnlNewTask.add(filler5, gridBagConstraints);

        cbNoPrice.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        cbNoPrice.setForeground(new java.awt.Color(255, 204, 204));
        cbNoPrice.setText(bundle.getString("BEZ CENY")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        pnlNewTask.add(cbNoPrice, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlNewTask, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 10.0;
        add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 10.0;
        add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filler3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        this.m.changeScreen("cardVyletDash");
    }//GEN-LAST:event_lblBackMouseReleased

    private void btnTaskCreateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskCreateMouseReleased
        String name = inputName.getText();
        String popis = inputDesc.getText();
        boolean pridat = cbWant.isSelected();
        boolean free = cbNoPrice.isSelected();
        Double cena = (Double)spinnerPrice.getValue();
        Vyletnik mojko = (Vyletnik) this.m.getHlavneOkno().getLoggedInPouzivatel();
        
        if (name.isEmpty() || popis.isEmpty()) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyplnte_nazov_popis"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletRozpocet] vytvorit task - nevyplneny nazov alebo popis; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        Uloha u = free ? new Uloha(mojko,name,popis) : new Uloha(mojko, name, popis, cena);
        if (pridat) {
            u.setVybavovac(mojko);
        }     
        v.pridajUlohu(u);
        refreshScren();
    }//GEN-LAST:event_btnTaskCreateMouseReleased

    private void btnTaskAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskAddMouseReleased
        Uloha u = listAllTasks.getSelectedValue();
        Vyletnik mojko = (Vyletnik) this.m.getHlavneOkno().getLoggedInPouzivatel();
        if (u == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyberte_ulohu"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletRozpocet] pridat task - nevybrana uloha; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        if (u.getVybavovac() != null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_uloha_zaobstarana"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletRozpocet] pridat task - uloha uz je zaobstarana; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        u.setVybavovac(mojko);
        DefaultListModel dlm_vu = (DefaultListModel)listYourTasks.getModel();
        dlm_vu.addElement(u);
        listAllTasks.clearSelection();
        pnlAllTasks.updateUI();
        CustomLogger.getLogger().log(Level.INFO, "[VyletRozpocet] pridany task; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
    }//GEN-LAST:event_btnTaskAddMouseReleased

    private void btnTaskCompleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskCompleteMouseReleased
        Uloha u = listYourTasks.getSelectedValue();
        if (u == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyberte_ulohu"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletRozpocet] complete task - nevybrana uloha; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        if (u.isZaobstarana()) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_uloha_splnena"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletRozpocet] complete task - uloha uz je splnena; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        u.setZaobstarana(true);
        listYourTasks.clearSelection();
        pnlYourTasks.updateUI();
        pnlAllTasks.updateUI();
        CustomLogger.getLogger().log(Level.INFO, "[VyletRozpocet] splnena uloha; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
    }//GEN-LAST:event_btnTaskCompleteMouseReleased
   
    private void refreshScren() {
        cbWant.setSelected(false);
        cbNoPrice.setSelected(false);
        inputName.setText("");
        inputDesc.setText("");
        spinnerPrice.setValue(0.00d);
        lblBudget.setText(v.getRozpocet().getSumaString()+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("€"));
        lblTasksTotal.setText(String.valueOf(v.getRozpocet().getZoznamUloh().size())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString(" (CELKOVO)"));
        lblBudgetPerMember.setText(v.getRozpocet().getSumaString(v.getPocetUcastnikov())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("€"));
        lblYourTasksCount.setText(String.valueOf(v.getRozpocet().getZoznamUloh((Vyletnik)this.m.getHlavneOkno().getLoggedInPouzivatel()).size())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString(" (VAŠICH)"));
        DefaultListModel dlm_au = (DefaultListModel)listAllTasks.getModel();
        dlm_au.removeAllElements();
        for (Uloha u : v.getRozpocet().getZoznamUloh())
            dlm_au.addElement(u);
        DefaultListModel dlm_vu = (DefaultListModel)listYourTasks.getModel();
        dlm_vu.removeAllElements();
        for (Uloha u : v.getRozpocet().getZoznamUloh((Vyletnik)m.getHlavneOkno().getLoggedInPouzivatel()))
            dlm_vu.addElement(u);
    }
    
    private void checkControls() {
        if (LocalDate.now().isAfter(v.getEndDate()) || v.isDokonceny()) {
            pnlNewTask.setVisible(false);
            btnTaskAdd.setVisible(false);
            btnTaskComplete.setVisible(false);
            GridBagLayout g = (GridBagLayout)this.getLayout();
            GridBagConstraints gc = g.getConstraints(pnlOverview);
            gc.gridwidth=2;
            g.setConstraints(pnlOverview, gc);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaskAdd;
    private javax.swing.JButton btnTaskComplete;
    private javax.swing.JButton btnTaskCreate;
    private javax.swing.JCheckBox cbNoPrice;
    private javax.swing.JCheckBox cbWant;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JTextField inputDesc;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel lblAllTasks;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblBudgetPerMember;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewTask;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTasks;
    private javax.swing.JLabel lblTasksTotal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVylet;
    private javax.swing.JLabel lblYouTasks;
    private javax.swing.JLabel lblYourTasksCount;
    private javax.swing.JList<Uloha> listAllTasks;
    private javax.swing.JList<Uloha> listYourTasks;
    private javax.swing.JPanel pnlAllTasks;
    private javax.swing.JPanel pnlNewTask;
    private javax.swing.JPanel pnlOverview;
    private javax.swing.JPanel pnlYourTasks;
    private javax.swing.JScrollPane scrollAllTasks;
    private javax.swing.JSpinner spinnerPrice;
    private javax.swing.JScrollPane srollYourTasks;
    // End of variables declaration//GEN-END:variables
}
