/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.vylet_dashboard;

import sk.stu.fiit.gui.utils.CellRenderers.UcastniciCellRenderer;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sk.stu.fiit.app.CustomLogger;
import sk.stu.fiit.app.trip.MiestoZaujmu;
import sk.stu.fiit.app.trip.Pozvanka;
import sk.stu.fiit.app.trip.Vylet;
import sk.stu.fiit.app.user.Vyletnik;
import sk.stu.fiit.gui.utils.CustomDialog;
import sk.stu.fiit.gui.utils.CustomScrollBarUI;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class VyletUcastniciPanel extends RoundedPanel {
    private VyletDashboardPanel m;
    private Vylet v;
    private boolean isListChanging = false;
    /**
     * Creates new form VyletMapaPanel
     */
    public VyletUcastniciPanel(VyletDashboardPanel m, Vylet v) {
        super(50, new Color(144,30,57,180));
        this.m = m; 
        this.v = v;
        setOpaque(false);
        initComponents();
        checkControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        scrollName = new javax.swing.JScrollPane();
        DefaultListModel dlm = new DefaultListModel<MiestoZaujmu>();
        listName = new javax.swing.JList<>(dlm);
        lblName = new javax.swing.JLabel();
        scrollDescription = new javax.swing.JScrollPane();
        inputDescription = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        lblInvTitle = new javax.swing.JLabel();
        pnlMembers = new RoundedPanel(25, new Color(0,0,0,100));
        scrollMembers = new javax.swing.JScrollPane();
        DefaultListModel dlm_vu = new DefaultListModel();
        for (Vyletnik vyletnik : v.getVeduci())
        dlm_vu.addElement(vyletnik);
        for (Vyletnik vyletnik : v.getPleby())
        dlm_vu.addElement(vyletnik);
        listMembers = new javax.swing.JList<>(dlm_vu);
        btnDerank = new javax.swing.JButton();
        btnRankup = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(200, 200, 200));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/previous.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblBack.setText(bundle.getString("SPÄŤ")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 10, 25);
        add(lblBack, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(bundle.getString("ÚČASTNÍCI")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        add(lblTitle, gridBagConstraints);

        inputName.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        inputName.setForeground(new java.awt.Color(101, 21, 40));
        inputName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputName.setPreferredSize(new java.awt.Dimension(160, 45));
        inputName.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (isListChanging) return;
                m.getHlavneOkno().getPotulkor().getZoznamVyletnikov((DefaultListModel)listName.getModel(),inputName.getText(), v);
                if (listName.getModel().getSize() > 0)
                scrollName.setVisible(true);

                updateUI();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (isListChanging) return;
                m.getHlavneOkno().getPotulkor().getZoznamVyletnikov((DefaultListModel)listName.getModel(),inputName.getText(), v);
                if (listName.getModel().getSize() > 0)
                scrollName.setVisible(true);
                else {
                    scrollName.setVisible(false);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        add(inputName, gridBagConstraints);

        scrollName.setVisible(false);
        scrollName.setBorder(null);
        scrollName.getViewport().setOpaque(false);
        scrollName.setViewportBorder(null);
        scrollName.getVerticalScrollBar().setPreferredSize(new Dimension(10, 0));
        scrollName.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        scrollName.setMaximumSize(new java.awt.Dimension(160, 100));
        scrollName.setMinimumSize(new java.awt.Dimension(160, 100));
        scrollName.setOpaque(false);
        scrollName.setPreferredSize(new java.awt.Dimension(160, 100));

        listName.setBackground(new Color(0,0,0,120));
        listName.setFont(new java.awt.Font("Gill Sans MT", 1, 22)); // NOI18N
        listName.setForeground(new java.awt.Color(255, 102, 102));
        listName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listName.setOpaque(false);
        listName.setPreferredSize(new java.awt.Dimension(160, 0));
        listName.setVisibleRowCount(5);
        listName.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()){
                    int index = listName.getSelectedIndex();
                    if (index >= 0){
                        Vyletnik vyletnik = (Vyletnik) ((DefaultListModel)listName.getModel()).getElementAt(index);
                        isListChanging = true;
                        inputName.setText(vyletnik.getCeleMeno());
                        inputName.requestFocusInWindow();
                        scrollName.setVisible(false);
                        isListChanging = false;
                    }
                }
            }
        });
        scrollName.setViewportView(listName);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        add(scrollName, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 102, 102));
        lblName.setText(bundle.getString("MENO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        add(lblName, gridBagConstraints);

        scrollDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollDescription.getViewport().setOpaque(false);
        scrollDescription.setViewportBorder(null);
        scrollDescription.getVerticalScrollBar().setPreferredSize(new Dimension(6, 0));
        scrollDescription.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        scrollDescription.setOpaque(false);

        inputDescription.setBackground(new Color(101, 21, 40, 120));
        inputDescription.setColumns(1);
        inputDescription.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        inputDescription.setForeground(new java.awt.Color(255, 204, 204));
        inputDescription.setLineWrap(true);
        inputDescription.setRows(4);
        inputDescription.setTabSize(4);
        inputDescription.setWrapStyleWord(true);
        scrollDescription.setViewportView(inputDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 30);
        add(scrollDescription, gridBagConstraints);

        btnSend.setBackground(new java.awt.Color(144, 30, 57));
        btnSend.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 204, 204));
        btnSend.setText(bundle.getString("ODOSLAŤ")); // NOI18N
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSendMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 40);
        add(btnSend, gridBagConstraints);

        lblDescription.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 102, 102));
        lblDescription.setText(bundle.getString("OBSAH")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(9, 25, 0, 0);
        add(lblDescription, gridBagConstraints);

        lblInvTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblInvTitle.setForeground(new java.awt.Color(255, 204, 204));
        lblInvTitle.setText(bundle.getString("POZVÁNKA")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        add(lblInvTitle, gridBagConstraints);

        pnlMembers.setOpaque(false);
        pnlMembers.setLayout(new java.awt.GridBagLayout());

        scrollMembers.setOpaque(false);
        scrollMembers.getViewport().setOpaque(false);
        scrollMembers.setViewportBorder(null);
        scrollMembers.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scrollMembers.setMinimumSize(new java.awt.Dimension(100, 80));
        scrollMembers.setOpaque(false);
        scrollMembers.setPreferredSize(new java.awt.Dimension(100, 0));
        scrollMembers.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        scrollMembers.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        listMembers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMembers.setOpaque(false);
        listMembers.setVisibleRowCount(4);
        listMembers.setCellRenderer(new UcastniciCellRenderer(v, 50, true));
        scrollMembers.setViewportView(listMembers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 25, 25);
        pnlMembers.add(scrollMembers, gridBagConstraints);

        btnDerank.setBackground(new java.awt.Color(144, 30, 57));
        btnDerank.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        btnDerank.setForeground(new java.awt.Color(255, 204, 204));
        btnDerank.setText(bundle.getString("ZNÍŽIŤ HODNOSŤ")); // NOI18N
        btnDerank.setMinimumSize(new java.awt.Dimension(142, 40));
        btnDerank.setPreferredSize(new java.awt.Dimension(142, 40));
        btnDerank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDerankMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(-15, 15, 10, 5);
        pnlMembers.add(btnDerank, gridBagConstraints);

        btnRankup.setBackground(new java.awt.Color(144, 30, 57));
        btnRankup.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        btnRankup.setForeground(new java.awt.Color(255, 204, 204));
        btnRankup.setText(bundle.getString("POVÝŠIŤ")); // NOI18N
        btnRankup.setMaximumSize(new java.awt.Dimension(142, 35));
        btnRankup.setMinimumSize(new java.awt.Dimension(142, 35));
        btnRankup.setPreferredSize(new java.awt.Dimension(142, 40));
        btnRankup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRankupMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(-15, 5, 10, 15);
        pnlMembers.add(btnRankup, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        add(pnlMembers, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.6;
        add(filler1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        this.m.changeScreen("cardVyletDash");
    }//GEN-LAST:event_lblBackMouseReleased

    private void btnSendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseReleased
        Vyletnik prijemca = listName.getSelectedValue();
        if (prijemca == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyber_pouzivatela"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] send inv - nevybraty prijemca; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        String popis = inputDescription.getText();
        if (popis.isEmpty()) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vypln_pozvanku"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] send inv - nevyplneny popis; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        if (prijemca.hasPozvanka(v)) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_pozvanka_existuje"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] send inv - pozvanka existuje us; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        Vyletnik od = (Vyletnik)this.m.getHlavneOkno().getLoggedInPouzivatel();
        od.posliPozvanku(new Pozvanka(od,prijemca,this.v,popis));
        inputDescription.setText("");
        isListChanging=true;
        inputName.setText("");
        isListChanging=false;
        new CustomDialog(this.getParent(), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("message_odoslana_pozvanka"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("OK"), JOptionPane.INFORMATION_MESSAGE);
        CustomLogger.getLogger().log(Level.INFO, "[VyletUcastnici] send inv - uspesne; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
    }//GEN-LAST:event_btnSendMouseReleased

    private void btnRankupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRankupMouseReleased
        Vyletnik vyletnik = listMembers.getSelectedValue();
        if (vyletnik == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_zvolte_ucastnika"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] rank up - nevybraty ucastnik; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
            return;
        }
        if (v.isVeduci(vyletnik)) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_ucastnik_je_veduci"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] rank up - ucastnik uz je veduci; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
            return;
        }
        v.povysVyletnika(vyletnik);
        checkControls();
        updateUI();
        CustomLogger.getLogger().log(Level.INFO, "[VyletUcastnici] rank up - ok; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
    }//GEN-LAST:event_btnRankupMouseReleased

    private void btnDerankMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDerankMouseReleased
        Vyletnik vyletnik = listMembers.getSelectedValue();
        if (vyletnik == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_zvolte_ucastnika"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] rank down - nevybraty ucastnik; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
            return;
        }
        if (v.isUcastnik(vyletnik)) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_ucastnik_nie_je_veduci"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] rank down - ucastnik uz je pleb; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
            return;
        }
        if (v.isZakladatel(vyletnik)) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_zakladatel_derank"),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"),JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletUcastnici] rank down - nemozno deranknut zakladatela; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
            return;
        }
        v.znizVeduceho(vyletnik);
        checkControls();
        updateUI();
        CustomLogger.getLogger().log(Level.INFO, "[VyletUcastnici] rank down - ok; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin() + " ;koho:" + vyletnik);
    }//GEN-LAST:event_btnDerankMouseReleased
 
    private void checkControls() {
        if (LocalDate.now().isAfter(v.getEndDate()) || v.isDokonceny()) {
            btnSend.setVisible(false);
            btnDerank.setVisible(false);
            btnRankup.setVisible(false);
            lblInvTitle.setVisible(false);
            lblName.setVisible(false);
            lblDescription.setVisible(false);
            inputName.setVisible(false);
            scrollName.setVisible(false);
            scrollDescription.setVisible(false);
        } else  {
            btnSend.setVisible(true);
            btnDerank.setVisible(v.isVeduci((Vyletnik)m.getHlavneOkno().getLoggedInPouzivatel()));
            btnRankup.setVisible(v.isVeduci((Vyletnik)m.getHlavneOkno().getLoggedInPouzivatel()));
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerank;
    private javax.swing.JButton btnRankup;
    private javax.swing.JButton btnSend;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextArea inputDescription;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblInvTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Vyletnik> listMembers;
    private javax.swing.JList<Vyletnik> listName;
    private javax.swing.JPanel pnlMembers;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JScrollPane scrollMembers;
    private javax.swing.JScrollPane scrollName;
    // End of variables declaration//GEN-END:variables
}
