/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.vylet_dashboard;

import sk.stu.fiit.gui.utils.CellRenderers.ItinerarCellRenderer;
import sk.stu.fiit.app.Potulkor;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sk.stu.fiit.app.CustomLogger;
import sk.stu.fiit.app.trip.Itinerar.ItinerarItem;
import sk.stu.fiit.app.trip.Vylet;
import sk.stu.fiit.gui.utils.CustomDialog;
import sk.stu.fiit.gui.utils.CustomScrollBarUI;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class VyletItinerarPanel extends RoundedPanel {
    private final VyletDashboardPanel m;
    private final Vylet v;
    /**
     * Creates new form VyletMapaPanel
     */
    public VyletItinerarPanel(VyletDashboardPanel m, Vylet v) {
        super(50, new Color(144,30,57,180));
        this.m = m; 
        this.v = v;
        setOpaque(false);
        initComponents();
        checkControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        pnlItinerary = new RoundedPanel(50, new Color(0,0,0,100));
        lblItinerary = new javax.swing.JLabel();
        scrollItinerary = new javax.swing.JScrollPane();
        DefaultListModel dlm_i = new DefaultListModel();
        for (ItinerarItem p : v.getItinerar().getItinerar())
        dlm_i.addElement(p);
        listItinerary = new javax.swing.JList<>(dlm_i);
        lblAddDate = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        spinnerDate = new javax.swing.JSpinner();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setLayout(new java.awt.GridBagLayout());

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(200, 200, 200));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/previous.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblBack.setText(bundle.getString("SPÄŤ")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 25);
        add(lblBack, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(bundle.getString("ITINERÁR")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        add(lblTitle, gridBagConstraints);

        lblDate.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 102, 102));
        lblDate.setText(bundle.getString("DÁTUM")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 0);
        add(lblDate, gridBagConstraints);

        btnAdd.setBackground(new java.awt.Color(144, 30, 57));
        btnAdd.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 204, 204));
        btnAdd.setText(bundle.getString("PRIDAŤ")); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 50);
        add(btnAdd, gridBagConstraints);

        pnlItinerary.setOpaque(false);
        pnlItinerary.setLayout(new java.awt.GridBagLayout());

        lblItinerary.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblItinerary.setForeground(new java.awt.Color(255, 204, 204));
        lblItinerary.setText(bundle.getString("ITINERÁR")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 0, 25);
        pnlItinerary.add(lblItinerary, gridBagConstraints);

        scrollItinerary.setOpaque(false);
        scrollItinerary.getViewport().setOpaque(false);
        scrollItinerary.setViewportBorder(null);
        scrollItinerary.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scrollItinerary.setMinimumSize(new java.awt.Dimension(100, 80));
        scrollItinerary.setOpaque(false);
        scrollItinerary.setPreferredSize(new java.awt.Dimension(100, 0));
        scrollItinerary.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        scrollItinerary.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        listItinerary.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listItinerary.setOpaque(false);
        listItinerary.setVisibleRowCount(4);
        listItinerary.setCellRenderer(new ItinerarCellRenderer());
        scrollItinerary.setViewportView(listItinerary);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 5, 25);
        pnlItinerary.add(scrollItinerary, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        add(pnlItinerary, gridBagConstraints);

        lblAddDate.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblAddDate.setForeground(new java.awt.Color(255, 204, 204));
        lblAddDate.setText(bundle.getString("PRIDANIE TERMÍNU")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 0);
        add(lblAddDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.3;
        add(filler1, gridBagConstraints);

        spinnerDate.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        spinnerDate.setModel(new javax.swing.SpinnerDateModel(Potulkor.toDate(v.getBeginDate().atTime(0,0)), Potulkor.toDate(v.getBeginDate().atTime(0, 0)), Potulkor.toDate(v.getEndDate().atTime(23, 59)), java.util.Calendar.HOUR_OF_DAY));
        spinnerDate.setPreferredSize(new java.awt.Dimension(185, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 50);
        add(spinnerDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.3;
        add(filler2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        this.m.changeScreen("cardVyletDash");          
    }//GEN-LAST:event_lblBackMouseReleased

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        ItinerarItem item = listItinerary.getSelectedValue();
        if (item == null) {
            new CustomDialog(this.getParent(),java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("error_vyberte_miesto"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("CHYBA"), JOptionPane.WARNING_MESSAGE);
            CustomLogger.getLogger().log(Level.WARNING, "[VyletItinerar] nevybrate miesto; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
            return;
        }
        
        item.setDatum(LocalDateTime.ofInstant(((Date)spinnerDate.getValue()).toInstant(), ZoneOffset.systemDefault()));
        spinnerDate.setValue(Potulkor.toDate(v.getBeginDate().atTime(0,0)));
        btnAdd.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("PRIDAŤ"));
        listItinerary.clearSelection();
        updateUI();
        new CustomDialog(this.getParent(), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("message_priradeny_termin"), java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("OK"), JOptionPane.INFORMATION_MESSAGE);
        CustomLogger.getLogger().log(Level.INFO, "[VyletItinerar] pridany termin; user:" + this.m.getHlavneOkno().getLoggedInPouzivatel().getLogin());
    }//GEN-LAST:event_btnAddMousePressed

    private void checkControls() {
        if (LocalDate.now().isAfter(v.getEndDate())) {
            lblAddDate.setVisible(false);
            lblDate.setVisible(false);
            spinnerDate.setVisible(false);
            btnAdd.setVisible(false);
        } else {
            listItinerary.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    if (!event.getValueIsAdjusting()){
                        ItinerarItem item = listItinerary.getSelectedValue();
                        if (item != null){
                            if (item.getDatum() == null) {
                                btnAdd.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("PRIDAŤ"));
                                ((SpinnerDateModel)spinnerDate.getModel()).setValue(((SpinnerDateModel)spinnerDate.getModel()).getStart());
                            } else {
                                btnAdd.setText(java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("UPRAVIŤ"));
                                ((SpinnerDateModel)spinnerDate.getModel()).setValue(Potulkor.toDate(item.getDatum()));
                            }
                        }
                    }
                }
            });
        }
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblAddDate;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblItinerary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<ItinerarItem> listItinerary;
    private javax.swing.JPanel pnlItinerary;
    private javax.swing.JScrollPane scrollItinerary;
    private javax.swing.JSpinner spinnerDate;
    // End of variables declaration//GEN-END:variables
}
