/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils.CellRenderers;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import sk.stu.fiit.app.trip.Pozvanka;
import sk.stu.fiit.app.user.Pouzivatel;
import sk.stu.fiit.gui.utils.RoundedImage;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class PozvankyCellRenderer extends JPanel implements ListCellRenderer<Pozvanka> {
    private int imageSize = 30;
    private Pouzivatel prijemca;
   
    public PozvankyCellRenderer() {
        initComponents();
    }
    
    public PozvankyCellRenderer(int imageSize, Pouzivatel p) {
        this.imageSize = imageSize;
        this.prijemca = p;
        initComponents();
        this.setPreferredSize(new Dimension(0,2*this.imageSize+(int)(2*this.imageSize*(1.0d/2))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContent = new RoundedPanel(this.imageSize-5, new Color(101, 21, 40));
        lblOdT = new javax.swing.JLabel();
        lblTripName = new javax.swing.JLabel();
        lblStatusIcon = new javax.swing.JLabel();
        lblKomuT = new javax.swing.JLabel();
        lblOd = new javax.swing.JLabel();
        lblKomu = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextArea();
        lblTripDate = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 40));
        setLayout(new java.awt.GridBagLayout());

        pnlContent.setOpaque(false);
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblOdT.setFont(new java.awt.Font("Gill Sans MT", 1, 22)); // NOI18N
        lblOdT.setForeground(new java.awt.Color(255, 102, 102));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblOdT.setText(bundle.getString("OD")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 0, 5);
        pnlContent.add(lblOdT, gridBagConstraints);

        lblTripName.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lblTripName.setForeground(new java.awt.Color(255, 102, 102));
        lblTripName.setText("Výlet");
        lblTripName.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTripName.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTripName.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 20);
        pnlContent.add(lblTripName, gridBagConstraints);

        lblStatusIcon.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblStatusIcon.setForeground(new java.awt.Color(255, 102, 102));
        lblStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/check.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        pnlContent.add(lblStatusIcon, gridBagConstraints);

        lblKomuT.setFont(new java.awt.Font("Gill Sans MT", 1, 22)); // NOI18N
        lblKomuT.setForeground(new java.awt.Color(255, 102, 102));
        lblKomuT.setText(bundle.getString("KOMU")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 8, 5);
        pnlContent.add(lblKomuT, gridBagConstraints);

        lblOd.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lblOd.setForeground(new java.awt.Color(255, 204, 204));
        lblOd.setText("Výlet");
        lblOd.setIconTextGap(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 0, 0);
        pnlContent.add(lblOd, gridBagConstraints);

        lblKomu.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lblKomu.setForeground(new java.awt.Color(255, 204, 204));
        lblKomu.setText("Výlet");
        lblKomu.setIconTextGap(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 8, 0);
        pnlContent.add(lblKomu, gridBagConstraints);

        textDesc.setEditable(false);
        textDesc.setBackground(new Color(0,0,0,0));
        textDesc.setColumns(1);
        textDesc.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        textDesc.setForeground(new java.awt.Color(255, 204, 204));
        textDesc.setLineWrap(true);
        textDesc.setRows(4);
        textDesc.setBorder(null);
        textDesc.setMinimumSize(new java.awt.Dimension(0, 0));
        textDesc.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 60);
        pnlContent.add(textDesc, gridBagConstraints);

        lblTripDate.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblTripDate.setForeground(new java.awt.Color(255, 204, 204));
        lblTripDate.setText("Výlet");
        lblTripDate.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTripDate.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTripDate.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 20);
        pnlContent.add(lblTripDate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        add(pnlContent, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getListCellRendererComponent(JList<? extends Pozvanka> list, Pozvanka value, int index, boolean isSelected, boolean cellHasFocus) {

        ((RoundedPanel)pnlContent).setBackgroundColor(new Color(101, 21, 40, 180));
        if (value.isPotvrdena()) {
            lblStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/check.png")));
        }  
        else if (value.isZamietnuta()) {
            lblStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/cancel.png")));
        }
        else {
            if (isSelected && (prijemca == null || (prijemca != null && value.getPrijemca().equals(prijemca)))) {
                ((RoundedPanel)pnlContent).setBackgroundColor(new Color(144,30,57,180));
            }
            lblStatusIcon.setIcon(null);
        }
        
        if (value.getOdosielatel().getObrazok() != null)
            lblOd.setIcon(RoundedImage.getImage(value.getOdosielatel().getObrazok(), this.imageSize));
        else
            lblOd.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/profile-user-256.png")).getImage().getScaledInstance(this.imageSize, this.imageSize, Image.SCALE_DEFAULT)));

        if (value.getPrijemca().getObrazok() != null)
            lblKomu.setIcon(RoundedImage.getImage(value.getPrijemca().getObrazok(), this.imageSize));
        else
            lblKomu.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/profile-user-256.png")).getImage().getScaledInstance(this.imageSize, this.imageSize, Image.SCALE_DEFAULT)));

        
        lblOd.setText(value.getOdosielatel().getCeleMeno());
        lblKomu.setText(value.getPrijemca().getCeleMeno());
        lblTripDate.setText(value.getVylet().getNazov());
        textDesc.setText(value.getSprava());
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblKomu;
    private javax.swing.JLabel lblKomuT;
    private javax.swing.JLabel lblOd;
    private javax.swing.JLabel lblOdT;
    private javax.swing.JLabel lblStatusIcon;
    private javax.swing.JLabel lblTripDate;
    private javax.swing.JLabel lblTripName;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTextArea textDesc;
    // End of variables declaration//GEN-END:variables
}
