/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils.CellRenderers;

import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import javafx.util.Pair;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import sk.stu.fiit.app.trip.MiestoZaujmu;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class TrasaCellRenderer extends javax.swing.JPanel implements ListCellRenderer<Pair<MiestoZaujmu,Double>> {

    /**
     * Creates new form TrasaCellRenderer
     */
    public TrasaCellRenderer() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContent = new RoundedPanel(25, new Color(101, 21, 40));
        lblPosition = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDistance = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(0, 45));
        setLayout(new java.awt.GridBagLayout());

        pnlContent.setMinimumSize(new java.awt.Dimension(0, 30));
        pnlContent.setOpaque(false);
        pnlContent.setPreferredSize(new java.awt.Dimension(0, 40));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblPosition.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(255, 204, 204));
        lblPosition.setText("#1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlContent.add(lblPosition, gridBagConstraints);

        lblName.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 204, 204));
        lblName.setText("Trencin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pnlContent.add(lblName, gridBagConstraints);

        lblDistance.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblDistance.setForeground(new java.awt.Color(212, 175, 55));
        lblDistance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDistance.setText("0 km");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlContent.add(lblDistance, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        add(pnlContent, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Pair<MiestoZaujmu, Double>> list, Pair<MiestoZaujmu, Double> value, int index, boolean isSelected, boolean cellHasFocus) {
        lblPosition.setText("#"+String.valueOf(index+1));
        lblName.setText(value.getKey().getName() == null ? "-" : value.getKey().getName());
        lblDistance.setText(new DecimalFormat("0.0").format(value.getValue())+"km");
        
        if (isSelected) {
            ((RoundedPanel)pnlContent).setBackgroundColor(new Color(144,30,57));
        } else { 
            ((RoundedPanel)pnlContent).setBackgroundColor(new Color(101, 21, 40));
        }
        return this;
    }
}
