/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui.utils.CellRenderers;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import sk.stu.fiit.app.trip.Uloha;
import sk.stu.fiit.gui.utils.RoundedImage;
import sk.stu.fiit.gui.utils.RoundedPanel;

/**
 *
 * @author dlhyl
 */
public class UlohyListCellRenderer extends JPanel implements ListCellRenderer<Uloha> {
    private final int iconSize = 25;
    /**
     * Creates new form VyletListCellRenderer
     */
    public UlohyListCellRenderer() {
        setOpaque(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContent = new RoundedPanel(25, new Color(101, 21, 40, 180));
        lblZadalC = new javax.swing.JLabel();
        lblZaobstaralC = new javax.swing.JLabel();
        lblNazov = new javax.swing.JLabel();
        lblKomentar = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        lblZaobstaral = new javax.swing.JLabel();
        lblZadal = new javax.swing.JLabel();
        lblZadal1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setMinimumSize(new java.awt.Dimension(0, 65));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 65));
        setLayout(new java.awt.GridBagLayout());

        pnlContent.setMinimumSize(new java.awt.Dimension(0, 65));
        pnlContent.setOpaque(false);
        pnlContent.setPreferredSize(new java.awt.Dimension(0, 65));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblZadalC.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblZadalC.setForeground(new java.awt.Color(255, 204, 204));
        lblZadalC.setText("Miro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        pnlContent.add(lblZadalC, gridBagConstraints);

        lblZaobstaralC.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblZaobstaralC.setForeground(new java.awt.Color(255, 204, 204));
        lblZaobstaralC.setText(" pansodadspisadiiads");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 3, 0);
        pnlContent.add(lblZaobstaralC, gridBagConstraints);

        lblNazov.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lblNazov.setForeground(new java.awt.Color(255, 102, 102));
        lblNazov.setText("Jedlo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 0, 0);
        pnlContent.add(lblNazov, gridBagConstraints);

        lblKomentar.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblKomentar.setForeground(new java.awt.Color(255, 204, 204));
        lblKomentar.setText("velaaaaaaaa velaaaaaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 0);
        pnlContent.add(lblKomentar, gridBagConstraints);

        lblCena.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblCena.setForeground(new java.awt.Color(255, 102, 102));
        lblCena.setText("2€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        pnlContent.add(lblCena, gridBagConstraints);

        lblZaobstaral.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblZaobstaral.setForeground(new java.awt.Color(255, 204, 204));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle"); // NOI18N
        lblZaobstaral.setText(bundle.getString("ZAOBSTARAL")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 3, 4);
        pnlContent.add(lblZaobstaral, gridBagConstraints);

        lblZadal.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblZadal.setForeground(new java.awt.Color(255, 204, 204));
        lblZadal.setText(bundle.getString("ZADAL")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 14, 0, 4);
        pnlContent.add(lblZadal, gridBagConstraints);

        lblZadal1.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblZadal1.setForeground(new java.awt.Color(255, 102, 102));
        lblZadal1.setMaximumSize(new java.awt.Dimension(16, 16));
        lblZadal1.setMinimumSize(new java.awt.Dimension(16, 16));
        lblZadal1.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 10);
        pnlContent.add(lblZadal1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlContent.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(pnlContent, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblKomentar;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblZadal;
    private javax.swing.JLabel lblZadal1;
    private javax.swing.JLabel lblZadalC;
    private javax.swing.JLabel lblZaobstaral;
    private javax.swing.JLabel lblZaobstaralC;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Uloha> list, Uloha value, int index, boolean isSelected, boolean cellHasFocus) {
               
        lblNazov.setText(value.getNazov());
        lblKomentar.setText(value.getKomentar());
        if (value.getCena() != null)
            lblCena.setText(new DecimalFormat("0.00").format(value.getCena().doubleValue())+java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("€"));
        else {
            lblCena.setText("");
        }
        lblZadalC.setText(value.getZadavatel().getMeno());
        
        if (value.getZadavatel().getObrazok() != null)
            lblZadalC.setIcon(RoundedImage.getImage(value.getZadavatel().getObrazok(), this.iconSize));
        else 
            lblZadalC.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/profile-user.png")).getImage().getScaledInstance(this.iconSize, this.iconSize, Image.SCALE_DEFAULT)));
        
        if (value.getVybavovac() != null) {
            lblZaobstaral.setText(value.isZaobstarana()?java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("ZAOBSTARAL"):java.util.ResourceBundle.getBundle("sk/stu/fiit/gui/bundle").getString("ZAOBSTARAVA"));
            lblZaobstaralC.setText(value.getVybavovac().getMeno());
            if (value.getVybavovac().getObrazok() != null)
                lblZaobstaralC.setIcon(RoundedImage.getImage(value.getVybavovac().getObrazok(), this.iconSize));
            else
                lblZaobstaralC.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/profile-user.png")).getImage().getScaledInstance(this.iconSize, this.iconSize, Image.SCALE_DEFAULT)));
        }  
        else {
            lblZaobstaral.setText("");
            lblZaobstaralC.setIcon(null);
            lblZaobstaralC.setText("");
        }
        
        if (value.isZaobstarana()) {
            ((RoundedPanel)pnlContent).setBackgroundColor(new Color(229, 204, 255,180));
            lblZadal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/assets/icons/check.png")));
        } else {
            lblZadal1.setIcon(null);
        }
        
        if (isSelected) {
            ((RoundedPanel)pnlContent).setBackgroundColor(new Color(144,30,57,180));
        } else {
            if (value.isZaobstarana())
                ((RoundedPanel)pnlContent).setBackgroundColor(new Color(81, 15, 30, 180));
            else 
                ((RoundedPanel)pnlContent).setBackgroundColor(new Color(101, 21, 40, 180));
            
        }
        return this;
    }
}
